version: '3'

volumes:
  php-fpm-socket:

services:
  app:
    image: mons9/codeigniter4:latest
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - ./src:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ci4_test
      - DB_USERNAME=ci4
      - DB_PASSWORD=Rg7-qYa4

  web:
    image: nginx:1.20
    ports: 
      - '80:80'
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./conf/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0.25
    ports: 
      - 3306:3306
    volumes:
      - ./mysql/var_lib_mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
        
    environment:
      MYSQL_ROOT_PASSWORD: Rg7-qYa4
      MYSQL_DATABASE: ci4_test
      MYSQL_USER: ci4
      MYSQL_PASSWORD: Rg7-qYa4

  phpmyadmin:
    image: phpmyadmin:5.1.1
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=ci4
      - PMA_PASSWORD=Rg7-qYa4
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"
